name: AfGLock
version: 1.7
author: halberfan | AfGMedia
main: de.afgmedia.afglock2.main.AfGLock
api-version: 1.19
load: POSTWORLD

commands:
    lock:
        description: Der wichtigste Befehl fürs Lock-Plugin

