name: AfGLock
version: ${project.version}
author: halberfan | AfGMedia
main: de.afgmedia.afglock2.main.AfGLock
api-version: 1.19
load: POSTWORLD
depend:
    - FTSUtils
    - ChestShop


commands:
    lock:
        description: Der wichtigste Befehl fürs Lock-Plugin
